### ISSUE TITLE
Bug: crash when trying to parse some APK files

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [hsiafan/apk-parser#125]
v2.6.10

Using my own test of going over all installed apps and their APK files ([here](https://github.com/AndroidDeveloperLB/apk-parser)), I've noticed that some APK files cause a crash when trying to parse them.

For example, I get this exception when trying to get the resource table:

```
E: FATAL EXCEPTION: Thread-2
    Process: com.lb.apkparser, PID: 27643
    java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:521)
        at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:258)
        at net.dongliu.apk.parser.utils.Buffers.readUShort(Buffers.java:25)
        at net.dongliu.apk.parser.parser.ResourceTableParser.readChunkHeader(ResourceTableParser.java:167)
        at net.dongliu.apk.parser.parser.ResourceTableParser.parse(ResourceTableParser.java:60)
        at com.lb.apkparser.apk_info.ApkInfo$Companion.getApkInfo(ApkInfo.kt:34)
        at com.lb.apkparser.MainActivity$performTest$1.invoke(MainActivity.kt:89)
        at com.lb.apkparser.MainActivity$performTest$1.invoke(MainActivity.kt:21)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
I: Sending signal. PID: 27643 SIG: 9
```

Attached here the problematic APK files:

[problematic apks.zip](https://github.com/hsiafan/apk-parser/files/4476682/problematic.apks.zip)

**Comment by AndroidDeveloperLB** [comment]
Seems his fix is correct, at least for :

/data/app/com.google.android.apps.playconsole--sdiPlkDE1yKnaudZA0HsQ==/split_foxcubsplitdeferral.config.xxhdpi.apk 

/data/app/com.google.android.networkstack-hhM1W4_a1HNYf10s26NtTQ==/split_config.xxhdpi.apk
