### ISSUE TITLE
NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by mehran75** [hsiafan/apk-parser#64]
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at net.dongliu.apk.parser.parser.ResourceTableParser.readChunkHeader(ResourceTableParser.java:173)
	at net.dongliu.apk.parser.parser.ResourceTableParser.parse(ResourceTableParser.java:51)
	at net.dongliu.apk.parser.AbstractApkFile.parseResourceTable(AbstractApkFile.java:248)
	at net.dongliu.apk.parser.AbstractApkFile.parseManifest(AbstractApkFile.java:104)
	at net.dongliu.apk.parser.AbstractApkFile.getApkMeta(AbstractApkFile.java:61)
	at server.NewUpdateController.chooseNewApk(NewUpdateController.java:47)

**Comment by hsiafan** [comment]
This bug was introduced in version 2.4.0, which is compiled with JDK9, due to Java9 change the return type of some ByteBuffer methods.
Now shoud be fixed in 2.4.1

**Comment by mehran75** [comment]
Thnaks
It works now.
