### ISSUE TITLE
get Unexpected chunk Type 0x0

### ISSUE THREAD

**Issue by momobile** [hsiafan/apk-parser#66]
[新建 WinRAR ZIP archive.zip](https://github.com/hsiafan/apk-parser/files/1526049/WinRAR.ZIP.archive.zip)

hello, try to parse apk attached with this issue, i got exception below;

in the same time, i try to use aapt or AXMLPrinter(also a project from github) can be parse without any error

can you help me trace the root cause and fix it ?  thanks a lot!!!

```
net.dongliu.apk.parser.exception.ParserException: Unexpected chunk Type: 0x0
	at net.dongliu.apk.parser.parser.ResourceTableParser.readChunkHeader(ResourceTableParser.java:221)
	at net.dongliu.apk.parser.parser.ResourceTableParser.readPackage(ResourceTableParser.java:92)
	at net.dongliu.apk.parser.parser.ResourceTableParser.parse(ResourceTableParser.java:61)
	at net.dongliu.apk.parser.AbstractApkFile.parseResourceTable(AbstractApkFile.java:248)
	at net.dongliu.apk.parser.AbstractApkFile.parseManifest(AbstractApkFile.java:104)
	at net.dongliu.apk.parser.AbstractApkFile.getApkMeta(AbstractApkFile.java:61)
```

**Comment by hsiafan** [comment]
There are paddings in the resource table, the bug is fixed in version 2.4.2.

**Comment by momobile** [comment]
when 2.4.2 will be release?

**Comment by hsiafan** [comment]
Sorry, should be 2.5.2. It has been released.
