### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by huangshaobb** [hsiafan/apk-parser#80]
When i parse the com.google.android.apps.giant apk

Exception in thread "main" java.lang.StackOverflowError
	at net.dongliu.apk.parser.struct.ResourceValue$ReferenceResourceValue.<init>(ResourceValue.java:127)
	at net.dongliu.apk.parser.struct.ResourceValue.reference(ResourceValue.java:46)
	at net.dongliu.apk.parser.utils.ParseUtils.readResValue(ParseUtils.java:170)
	at net.dongliu.apk.parser.struct.resource.Type.readResourceEntry(Type.java:78)
	at net.dongliu.apk.parser.struct.resource.Type.getResourceEntry(Type.java:46)
	at net.dongliu.apk.parser.struct.resource.ResourceTable.getResourcesById(ResourceTable.java:68)
	at net.dongliu.apk.parser.struct.ResourceValue$ReferenceResourceValue.toStringValue(ResourceValue.java:146)
	at net.dongliu.apk.parser.struct.resource.ResourceEntry.toStringValue(ResourceEntry.java:42)
	at net.dongliu.apk.parser.struct.ResourceValue$ReferenceResourceValue.toStringValue(ResourceValue.java:170)
	at net.dongliu.apk.parser.struct.resource.ResourceEntry.toStringValue(ResourceEntry.java:42)
	at net.dongliu.apk.parser.struct.ResourceValue$ReferenceResourceValue.toStringValue(ResourceValue.java:170)
	at net.dongliu.apk.parser.struct.resource.ResourceEntry.toStringValue(ResourceEntry.java:42)
	at net.dongliu.apk.parser.struct.ResourceValue$ReferenceResourceValue.toStringValue(ResourceValue.java:170)
	at net.dongliu.apk.parser.struct.resource.ResourceEntry.toStringValue(ResourceEntry.java:42)
	at net.dongliu.apk.parser.struct.ResourceValue$ReferenceResourceValue.toStringValue(ResourceValue.java:170)
	at net.dongliu.apk.parser.struct.resource.ResourceEntry.toStringValue(ResourceEntry.java:42)

**Comment by huangshaobb** [comment]
// cyclic reference detect
            if (currentResourceValue instanceof ResourceValue.ReferenceResourceValue) {
                if (resourceId == ((ResourceValue.ReferenceResourceValue) currentResourceValue)
                        .getReferenceResourceId()) {
                    continue;
                }
            }

I found different resourceId cyclic refrence

**Comment by huangshaobb** [comment]
> Would you please provide the apk file cause the problem? I download one but it works all right.

Ok,how to give the apk to you

**Comment by huangshaobb** [comment]
> Would you please provide the apk file cause the problem? I download one but it works all right.

https://drive.google.com/open?id=1AnJM0l1z8SFcrxd8o9nAtpaY2_Sa-VQ2

**Comment by hsiafan** [comment]
fix in https://github.com/hsiafan/apk-parser/commit/f23aa00fc0045391b4413374bb671b0d1422bf74 .
Try new version 2.6.4

**Comment by huangshaobb** [comment]
> fix in [f23aa00](https://github.com/hsiafan/apk-parser/commit/f23aa00fc0045391b4413374bb671b0d1422bf74) .
> Try new version 2.6.4
Thanks! By the way, https://mvnrepository.com/artifact/net.dongliu/apk-parser not found the ver 2.6.4

**Comment by hsiafan** [comment]
mvnrepository.com is a third-party maven index site,  it has latency for one or several hours.
