### ISSUE TITLE
输出v1签名报错，up主帮忙看下

### ISSUE THREAD

**Issue by xlc1540697096** [hsiafan/apk-parser#88]
我的环境：
```
$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)
```

Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at net.dongliu.apk.parser.cert.asn1.ber.ByteBufferBerDataValueReader.skipDefiniteLengthContents(ByteBufferBerDataValueReader.java:157)
        at net.dongliu.apk.parser.cert.asn1.ber.ByteBufferBerDataValueReader.readDataValue(ByteBufferBerDataValueReader.java:60)
        at net.dongliu.apk.parser.cert.asn1.Asn1BerParser.parse(Asn1BerParser.java:61)
        at net.dongliu.apk.parser.parser.JSSECertificateParser.parse(JSSECertificateParser.java:34)
        at net.dongliu.apk.parser.AbstractApkFile.parseCertificates(AbstractApkFile.java:131)

**Comment by hsiafan** [comment]
用了高版本jdk编译引起的问题，重新发了一个版本2.6.6，试试看

**Comment by xlc1540697096** [comment]
现在发新版了吗？
我在maven中央仓库还没有找到
https://mvnrepository.com/artifact/net.dongliu/apk-parser

**Comment by hsiafan** [comment]
已经发了。mvnrepository是个第三方的索引库，更新比较慢
