### ISSUE TITLE
Unexpected chunk Type:204

### ISSUE THREAD

**Issue by naynus** [hsiafan/apk-parser#89]
When I used the tool to parse the apk of package "com.android.documentui" on Anroid Q,  I got the following issue:
Exception in thread "main" net.dongliu.apk.parser.exception.ParserException: Unexpected chunk Type: 0x204
	at net.dongliu.apk.parser.parser.ResourceTableParser.readChunkHeader(ResourceTableParser.java:223)	at net.dongliu.apk.parser.parser.ResourceTableParser.readPackage(ResourceTableParser.java:91)
	at net.dongliu.apk.parser.parser.ResourceTableParser.parse(ResourceTableParser.java:60)
	at net.dongliu.apk.parser.AbstractApkFile.parseResourceTable(AbstractApkFile.java:391)
	at net.dongliu.apk.parser.AbstractApkFile.parseManifest(AbstractApkFile.java:188)
	at net.dongliu.apk.parser.AbstractApkFile.getManifestXml(AbstractApkFile.java:59)

**Comment by hsiafan** [comment]
Would you please provide a link to get the apk file?

**Comment by hsiafan** [comment]
type new version 2.6.8
