### ISSUE TITLE
apkFileInfo.getApkSingers:java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by lambertlei** [hsiafan/apk-parser#91]
version:2.6.5
jdk:1.7
error msg:
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at net.dongliu.apk.parser.cert.asn1.ber.ByteBufferBerDataValueReader.skipDefiniteLengthContents(ByteBufferBerDataValueReader.java:157)
	at net.dongliu.apk.parser.cert.asn1.ber.ByteBufferBerDataValueReader.readDataValue(ByteBufferBerDataValueReader.java:60)
	at net.dongliu.apk.parser.cert.asn1.Asn1BerParser.parse(Asn1BerParser.java:61)
	at net.dongliu.apk.parser.parser.JSSECertificateParser.parse(JSSECertificateParser.java:34)
	at net.dongliu.apk.parser.AbstractApkFile.parseCertificates(AbstractApkFile.java:131)
	at net.dongliu.apk.parser.AbstractApkFile.getApkSingers(AbstractApkFile.java:122)

**Comment by hsiafan** [comment]
Please try version 2.6.6.
This has been fixed in new version, i forgot to update readme file.

**Comment by lambertlei** [comment]
is work.thanks!
